name: Sampa

exclude: [bibble, README.md, Makefile]

# use this library to parse Markdown
markdown: redcarpet

# colorize code snippets with the pygment module
pygments: true

# Sections on the "people" page.
roles:
    - {key: faculty, name: Faculty}
    - {key: staff, name: Staff}
    - {key: postdoc, name: Researchers}
    - {key: grad, name: Graduate Students}

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''
