name: SAMPA

# use this library to parse Markdown
markdown: redcarpet

# colorize code snippets with the pygment module
pygments: true

roles:
    - {key: faculty, name: Faculty}
    - {key: postdoc, name: Researchers}
    - {key: grad, name: Grad Students}
