name: Sampa

# use this library to parse Markdown
markdown: redcarpet

# colorize code snippets with the pygment module
pygments: true

roles:
    - {key: faculty, name: Faculty}
    - {key: staff, name: Staff}
    - {key: postdoc, name: Researchers}
    - {key: grad, name: Graduate Students}

front_page_news: 8
base: ''
